# Generated by Django 5.1.1 on 2024-09-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('financial-accounting', 'Financial Accounting'), ('marketing-management', 'Marketing Management'), ('strategic-management', 'Strategic Management'), ('business-law', 'Business Law'), ('international-business', 'International Business')], max_length=30)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('standard', 'Standard'), ('advanced', 'Advanced')], max_length=30)),
                ('time_required', models.CharField(choices=[('1hr', '1hr'), ('1-3hr', '1-3hr'), ('3-6hr', '3-6hr')], max_length=30)),
                ('session_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Any time', 'Any time')], max_length=30)),
            ],
        ),
    ]
